#!/usr/bin/env python3
"""Prepare a manifest-driven Remotion project for the lightweight Vlog flow."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

FPS = 30
DEFAULT_WIDTH = 1920
DEFAULT_HEIGHT = 1080


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Remotion assets and source files for a Vlog project.")
    parser.add_argument("project", type=Path, help="Project folder containing camera/, screen/, screenshots/.")
    parser.add_argument("--manifest", type=Path, required=True, help="Manifest JSON generated by build_vlog_manifest.py.")
    parser.add_argument("--subtitles", type=Path, required=True, help="Subtitle JSON generated by segment_subtitles.py.")
    parser.add_argument("--remotion-dir", type=Path, default=Path("remotion-project"))
    parser.add_argument("--width", type=int, default=DEFAULT_WIDTH)
    parser.add_argument("--height", type=int, default=DEFAULT_HEIGHT)
    return parser.parse_args()


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def video_duration(path: Path) -> float:
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-show_entries",
                "format=duration",
                "-of",
                "default=noprint_wrappers=1:nokey=1",
                str(path),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        return max(0.1, float(result.stdout.strip()))
    except FileNotFoundError:
        fail("ffprobe not found. Install ffmpeg first.")
    except (subprocess.CalledProcessError, ValueError) as exc:
        fail(f"Could not read video duration for {path}: {exc}")


def safe_name(index: int, source: Path) -> str:
    suffix = source.suffix.lower() or ".bin"
    return f"{index:03d}-{source.stem[:48]}{suffix}"


def load_json(path: Path) -> Any:
    if not path.is_file():
        fail(f"File not found: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"Malformed JSON in {path}: {exc}")


def build_timeline(project: Path, manifest: dict[str, Any], public_dir: Path) -> tuple[list[dict[str, Any]], float]:
    raw_timeline = manifest.get("timeline")
    if not isinstance(raw_timeline, list) or not raw_timeline:
        fail("Manifest timeline is empty.")

    public_dir.mkdir(parents=True, exist_ok=True)
    timeline: list[dict[str, Any]] = []
    cursor = 0.0

    for index, item in enumerate(raw_timeline):
        if not isinstance(item, dict):
            continue
        source_value = item.get("source")
        asset_type = item.get("type")
        if not isinstance(source_value, str) or asset_type not in {"video", "image"}:
            continue

        source = project / source_value
        if not source.is_file():
            fail(f"Asset listed in manifest is missing: {source}")

        destination_name = safe_name(index, source)
        shutil.copy2(source, public_dir / destination_name)

        if asset_type == "video":
            duration = video_duration(source)
        else:
            duration = float(item.get("durationSeconds", 5.0))
            duration = max(0.5, duration)

        timeline.append(
            {
                "id": index,
                "type": asset_type,
                "role": str(item.get("role", "asset")),
                "src": destination_name,
                "start": round(cursor, 3),
                "duration": round(duration, 3),
                "motion": str(item.get("motion", "none")),
            }
        )
        cursor += duration

    if not timeline:
        fail("No valid assets were prepared.")
    return timeline, cursor


def root_tsx(width: int, height: int, duration_frames: int) -> str:
    return f'''import React from "react";
import {{Composition}} from "remotion";
import {{VlogVideo}} from "./VlogVideo";

export const RemotionRoot: React.FC = () => (
  <Composition
    id="VlogVideo"
    component={{VlogVideo}}
    fps={{{FPS}}}
    width={{{width}}}
    height={{{height}}}
    durationInFrames={{{duration_frames}}}
  />
);
'''


def vlog_tsx() -> str:
    return '''import React from "react";
import {
  AbsoluteFill,
  Img,
  OffthreadVideo,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
} from "remotion";
import timeline from "../public/vlog/timeline.json";
import subtitles from "../public/vlog/subtitles.json";

type TimelineItem = {
  id: number;
  type: "video" | "image";
  role: string;
  src: string;
  start: number;
  duration: number;
  motion: string;
};

type SubtitleItem = {
  id: number;
  start: number;
  end: number;
  lines: string[];
  fontSize: number;
};

const FPS = 30;
const media = timeline as TimelineItem[];
const captions = subtitles as SubtitleItem[];

const fitStyle: React.CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "contain",
};

const Still: React.FC<{item: TimelineItem}> = ({item}) => {
  const frame = useCurrentFrame();
  const localDuration = Math.max(1, Math.round(item.duration * FPS));
  const scale = item.motion === "slow-pan"
    ? interpolate(frame, [0, localDuration], [1.0, 1.06], {extrapolateRight: "clamp"})
    : 1;
  return (
    <AbsoluteFill style={{backgroundColor: "#05070a", overflow: "hidden"}}>
      <Img src={staticFile(`vlog/assets/${item.src}`)} style={{...fitStyle, transform: `scale(${scale})`}} />
    </AbsoluteFill>
  );
};

export const VlogVideo: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill style={{backgroundColor: "black"}}>
      {media.map((item) => {
        const from = Math.round(item.start * FPS);
        const durationInFrames = Math.max(1, Math.round(item.duration * FPS));
        return (
          <Sequence key={item.id} from={from} durationInFrames={durationInFrames}>
            {item.type === "video" ? (
              <OffthreadVideo src={staticFile(`vlog/assets/${item.src}`)} style={fitStyle} />
            ) : (
              <Still item={item} />
            )}
          </Sequence>
        );
      })}

      {captions.map((caption) => {
        const from = Math.round(caption.start * FPS);
        const durationInFrames = Math.max(1, Math.round((caption.end - caption.start) * FPS));
        if (frame < from || frame >= from + durationInFrames) return null;
        return (
          <Sequence key={caption.id} from={from} durationInFrames={durationInFrames}>
            <AbsoluteFill style={{justifyContent: "flex-end", alignItems: "center", paddingBottom: 54}}>
              <div style={{
                maxWidth: "88%",
                padding: "12px 22px",
                borderRadius: 14,
                backgroundColor: "rgba(0,0,0,0.72)",
                color: "white",
                fontSize: Math.min(caption.fontSize, 56),
                fontWeight: 800,
                lineHeight: 1.25,
                textAlign: "center",
                whiteSpace: "pre-line",
                textShadow: "0 2px 8px rgba(0,0,0,0.9)",
              }}>{caption.lines.join("\\n")}</div>
            </AbsoluteFill>
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
'''


def index_ts() -> str:
    return '''import {registerRoot} from "remotion";
import {RemotionRoot} from "./Root";
registerRoot(RemotionRoot);
'''


def main() -> None:
    args = parse_args()
    project = args.project.resolve()
    manifest_path = args.manifest.resolve()
    subtitles_path = args.subtitles.resolve()
    remotion_dir = args.remotion_dir.resolve()

    if not project.is_dir():
        fail(f"Project folder not found: {project}")

    manifest = load_json(manifest_path)
    subtitles = load_json(subtitles_path)
    if not isinstance(manifest, dict):
        fail("Manifest must be a JSON object.")
    if not isinstance(subtitles, list):
        fail("Subtitles must be a JSON list.")

    public_vlog = remotion_dir / "public" / "vlog"
    assets_dir = public_vlog / "assets"
    if assets_dir.exists():
        shutil.rmtree(assets_dir)

    timeline, total_seconds = build_timeline(project, manifest, assets_dir)
    public_vlog.mkdir(parents=True, exist_ok=True)
    (public_vlog / "timeline.json").write_text(json.dumps(timeline, ensure_ascii=False, indent=2), encoding="utf-8")
    (public_vlog / "subtitles.json").write_text(json.dumps(subtitles, ensure_ascii=False, indent=2), encoding="utf-8")

    src_dir = remotion_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    duration_frames = max(1, round(total_seconds * FPS))
    (src_dir / "Root.tsx").write_text(root_tsx(args.width, args.height, duration_frames), encoding="utf-8")
    (src_dir / "VlogVideo.tsx").write_text(vlog_tsx(), encoding="utf-8")
    (src_dir / "index.ts").write_text(index_ts(), encoding="utf-8")

    print(f"Prepared {len(timeline)} timeline items")
    print(f"Total duration: {total_seconds:.3f} sec")
    print(f"Frames: {duration_frames}")
    print(f"Remotion project: {remotion_dir}")


if __name__ == "__main__":
    main()
